import {
  formatColors,
  formatFontFamily,
  formatFontWeight,
  formatFontSize,
  formatSafelist,
} from "./format-theme";

test("format colors", () => {
  const result = formatColors([
    { name: "Primary", value: "#ff0000" },
    { name: "Secondary", value: "#0000ff" },
  ]);

  expect(result).toEqual({
    primary: "#ff0000",
    secondary: "#0000ff",
    white: "#ffffff",
    black: "#000000",
  });
});

test("format font family", () => {
  const result = formatFontFamily([
    { name: "Primary", value: "Arial, sans-serif" },
    { name: "Secondary", value: "Helvetica, sans-serif" },
  ]);

  expect(result).toEqual({
    primary: ["Arial", "sans-serif"],
    secondary: ["Helvetica", "sans-serif"],
  });
});

test("format font weight", () => {
  const result = formatFontWeight([
    { name: "thin", value: "200" },
    { name: "bold", value: "600" },
  ]);

  expect(result).toEqual({
    thin: 200,
    bold: 600,
  });
});

test("format font size", () => {
  const result = formatFontSize([
    { name: "xs", size: "10px" },
    { name: "sm", size: "0.75rem", lineHeight: "1rem" },
    {
      name: "md",
      size: "0.875rem",
      lineHeight: "1.25rem",
      letterSpacing: "0.01em",
      fontWeight: "400",
    },
  ]);

  expect(result).toEqual({
    xs: "10px",
    sm: ["0.75rem", { lineHeight: "1rem" }],
    md: [
      "0.875rem",
      {
        lineHeight: "1.25rem",
        letterSpacing: "0.01em",
        fontWeight: "400",
      },
    ],
  });
});

test("generate safelist", () => {
  const result = formatSafelist({
    colors: {
      red: "#ff0000",
      blue: "#0000ff",
    },
    fontFamily: {
      primary: ["Arial", "sans-serif"],
      secondary: ["Helvetica", "sans-serif"],
    },
    fontWeight: {
      thin: 200,
      bold: 600,
    },
    fontSize: {
      xs: "10px",
      sm: "12px",
    },
  });

  expect(result).toEqual([
    "bg-red",
    "sm:bg-red",
    "md:bg-red",
    "lg:bg-red",
    "xl:bg-red",
    "2xl:bg-red",
    "bg-blue",
    "sm:bg-blue",
    "md:bg-blue",
    "lg:bg-blue",
    "xl:bg-blue",
    "2xl:bg-blue",
    "text-red",
    "sm:text-red",
    "md:text-red",
    "lg:text-red",
    "xl:text-red",
    "2xl:text-red",
    "text-blue",
    "sm:text-blue",
    "md:text-blue",
    "lg:text-blue",
    "xl:text-blue",
    "2xl:text-blue",
    "border-red",
    "sm:border-red",
    "md:border-red",
    "lg:border-red",
    "xl:border-red",
    "2xl:border-red",
    "border-blue",
    "sm:border-blue",
    "md:border-blue",
    "lg:border-blue",
    "xl:border-blue",
    "2xl:border-blue",
    "divide-red",
    "sm:divide-red",
    "md:divide-red",
    "lg:divide-red",
    "xl:divide-red",
    "2xl:divide-red",
    "divide-blue",
    "sm:divide-blue",
    "md:divide-blue",
    "lg:divide-blue",
    "xl:divide-blue",
    "2xl:divide-blue",
    "font-primary",
    "sm:font-primary",
    "md:font-primary",
    "lg:font-primary",
    "xl:font-primary",
    "2xl:font-primary",
    "font-secondary",
    "sm:font-secondary",
    "md:font-secondary",
    "lg:font-secondary",
    "xl:font-secondary",
    "2xl:font-secondary",
    "font-thin",
    "sm:font-thin",
    "md:font-thin",
    "lg:font-thin",
    "xl:font-thin",
    "2xl:font-thin",
    "font-bold",
    "sm:font-bold",
    "md:font-bold",
    "lg:font-bold",
    "xl:font-bold",
    "2xl:font-bold",
    "text-xs",
    "sm:text-xs",
    "md:text-xs",
    "lg:text-xs",
    "xl:text-xs",
    "2xl:text-xs",
    "text-sm",
    "sm:text-sm",
    "md:text-sm",
    "lg:text-sm",
    "xl:text-sm",
    "2xl:text-sm",
    "px-0",
    "sm:px-0",
    "md:px-0",
    "lg:px-0",
    "xl:px-0",
    "2xl:px-0",
    "px-1",
    "sm:px-1",
    "md:px-1",
    "lg:px-1",
    "xl:px-1",
    "2xl:px-1",
    "px-2",
    "sm:px-2",
    "md:px-2",
    "lg:px-2",
    "xl:px-2",
    "2xl:px-2",
    "px-3",
    "sm:px-3",
    "md:px-3",
    "lg:px-3",
    "xl:px-3",
    "2xl:px-3",
    "px-4",
    "sm:px-4",
    "md:px-4",
    "lg:px-4",
    "xl:px-4",
    "2xl:px-4",
    "px-5",
    "sm:px-5",
    "md:px-5",
    "lg:px-5",
    "xl:px-5",
    "2xl:px-5",
    "px-6",
    "sm:px-6",
    "md:px-6",
    "lg:px-6",
    "xl:px-6",
    "2xl:px-6",
    "px-7",
    "sm:px-7",
    "md:px-7",
    "lg:px-7",
    "xl:px-7",
    "2xl:px-7",
    "px-8",
    "sm:px-8",
    "md:px-8",
    "lg:px-8",
    "xl:px-8",
    "2xl:px-8",
    "px-9",
    "sm:px-9",
    "md:px-9",
    "lg:px-9",
    "xl:px-9",
    "2xl:px-9",
    "px-10",
    "sm:px-10",
    "md:px-10",
    "lg:px-10",
    "xl:px-10",
    "2xl:px-10",
    "px-11",
    "sm:px-11",
    "md:px-11",
    "lg:px-11",
    "xl:px-11",
    "2xl:px-11",
    "px-12",
    "sm:px-12",
    "md:px-12",
    "lg:px-12",
    "xl:px-12",
    "2xl:px-12",
    "px-14",
    "sm:px-14",
    "md:px-14",
    "lg:px-14",
    "xl:px-14",
    "2xl:px-14",
    "px-16",
    "sm:px-16",
    "md:px-16",
    "lg:px-16",
    "xl:px-16",
    "2xl:px-16",
    "px-px",
    "sm:px-px",
    "md:px-px",
    "lg:px-px",
    "xl:px-px",
    "2xl:px-px",
    "px-0.5",
    "sm:px-0.5",
    "md:px-0.5",
    "lg:px-0.5",
    "xl:px-0.5",
    "2xl:px-0.5",
    "px-1.5",
    "sm:px-1.5",
    "md:px-1.5",
    "lg:px-1.5",
    "xl:px-1.5",
    "2xl:px-1.5",
    "px-2.5",
    "sm:px-2.5",
    "md:px-2.5",
    "lg:px-2.5",
    "xl:px-2.5",
    "2xl:px-2.5",
    "px-3.5",
    "sm:px-3.5",
    "md:px-3.5",
    "lg:px-3.5",
    "xl:px-3.5",
    "2xl:px-3.5",
    "py-0",
    "sm:py-0",
    "md:py-0",
    "lg:py-0",
    "xl:py-0",
    "2xl:py-0",
    "py-1",
    "sm:py-1",
    "md:py-1",
    "lg:py-1",
    "xl:py-1",
    "2xl:py-1",
    "py-2",
    "sm:py-2",
    "md:py-2",
    "lg:py-2",
    "xl:py-2",
    "2xl:py-2",
    "py-3",
    "sm:py-3",
    "md:py-3",
    "lg:py-3",
    "xl:py-3",
    "2xl:py-3",
    "py-4",
    "sm:py-4",
    "md:py-4",
    "lg:py-4",
    "xl:py-4",
    "2xl:py-4",
    "py-5",
    "sm:py-5",
    "md:py-5",
    "lg:py-5",
    "xl:py-5",
    "2xl:py-5",
    "py-6",
    "sm:py-6",
    "md:py-6",
    "lg:py-6",
    "xl:py-6",
    "2xl:py-6",
    "py-7",
    "sm:py-7",
    "md:py-7",
    "lg:py-7",
    "xl:py-7",
    "2xl:py-7",
    "py-8",
    "sm:py-8",
    "md:py-8",
    "lg:py-8",
    "xl:py-8",
    "2xl:py-8",
    "py-9",
    "sm:py-9",
    "md:py-9",
    "lg:py-9",
    "xl:py-9",
    "2xl:py-9",
    "py-10",
    "sm:py-10",
    "md:py-10",
    "lg:py-10",
    "xl:py-10",
    "2xl:py-10",
    "py-11",
    "sm:py-11",
    "md:py-11",
    "lg:py-11",
    "xl:py-11",
    "2xl:py-11",
    "py-12",
    "sm:py-12",
    "md:py-12",
    "lg:py-12",
    "xl:py-12",
    "2xl:py-12",
    "py-14",
    "sm:py-14",
    "md:py-14",
    "lg:py-14",
    "xl:py-14",
    "2xl:py-14",
    "py-16",
    "sm:py-16",
    "md:py-16",
    "lg:py-16",
    "xl:py-16",
    "2xl:py-16",
    "py-px",
    "sm:py-px",
    "md:py-px",
    "lg:py-px",
    "xl:py-px",
    "2xl:py-px",
    "py-0.5",
    "sm:py-0.5",
    "md:py-0.5",
    "lg:py-0.5",
    "xl:py-0.5",
    "2xl:py-0.5",
    "py-1.5",
    "sm:py-1.5",
    "md:py-1.5",
    "lg:py-1.5",
    "xl:py-1.5",
    "2xl:py-1.5",
    "py-2.5",
    "sm:py-2.5",
    "md:py-2.5",
    "lg:py-2.5",
    "xl:py-2.5",
    "2xl:py-2.5",
    "py-3.5",
    "sm:py-3.5",
    "md:py-3.5",
    "lg:py-3.5",
    "xl:py-3.5",
    "2xl:py-3.5",
    "border-0",
    "sm:border-0",
    "md:border-0",
    "lg:border-0",
    "xl:border-0",
    "2xl:border-0",
    "border-2",
    "sm:border-2",
    "md:border-2",
    "lg:border-2",
    "xl:border-2",
    "2xl:border-2",
    "border-4",
    "sm:border-4",
    "md:border-4",
    "lg:border-4",
    "xl:border-4",
    "2xl:border-4",
    "border-8",
    "sm:border-8",
    "md:border-8",
    "lg:border-8",
    "xl:border-8",
    "2xl:border-8",
    "border-px",
    "sm:border-px",
    "md:border-px",
    "lg:border-px",
    "xl:border-px",
    "2xl:border-px",
    "rounded-none",
    "sm:rounded-none",
    "md:rounded-none",
    "lg:rounded-none",
    "xl:rounded-none",
    "2xl:rounded-none",
    "rounded-sm",
    "sm:rounded-sm",
    "md:rounded-sm",
    "lg:rounded-sm",
    "xl:rounded-sm",
    "2xl:rounded-sm",
    "rounded-md",
    "sm:rounded-md",
    "md:rounded-md",
    "lg:rounded-md",
    "xl:rounded-md",
    "2xl:rounded-md",
    "rounded-lg",
    "sm:rounded-lg",
    "md:rounded-lg",
    "lg:rounded-lg",
    "xl:rounded-lg",
    "2xl:rounded-lg",
    "rounded-xl",
    "sm:rounded-xl",
    "md:rounded-xl",
    "lg:rounded-xl",
    "xl:rounded-xl",
    "2xl:rounded-xl",
    "rounded-2xl",
    "sm:rounded-2xl",
    "md:rounded-2xl",
    "lg:rounded-2xl",
    "xl:rounded-2xl",
    "2xl:rounded-2xl",
    "rounded-3xl",
    "sm:rounded-3xl",
    "md:rounded-3xl",
    "lg:rounded-3xl",
    "xl:rounded-3xl",
    "2xl:rounded-3xl",
    "rounded-full",
    "sm:rounded-full",
    "md:rounded-full",
    "lg:rounded-full",
    "xl:rounded-full",
    "2xl:rounded-full",
  ]);
});
