import { LanguagesListType } from "../../languages";
import { write } from "../utils/is-write";
import {
  formatColors,
  formatFontFamily,
  formatFontSize,
  formatFontWeight,
  formatSafelist,
} from "./format-theme";

const cp = require("child_process");

const DO_NOT_EDIT_FLAG = `// NOTE: This file is auto generated and should not be edited!`;

const PicoSanity = require("picosanity");
const fs = require("fs").promises;

const client = new PicoSanity({
  dataset: process.env.NEXT_PUBLIC_SANITY_DATASET || "development",
  projectId: process.env.NEXT_PUBLIC_SANITY_PROJECT_ID || "",
  apiVersion: "2021-03-25",
  useCdn: process.env.NODE_ENV === "production",
});

export type GroqThemeType = {
  colors: { name: string; value: string }[];
  fontFamily: { name: string; value: string }[];
  fontSize: {
    name: string;
    size: string;
    lineHeight?: string;
    letterSpacing?: string;
    fontWeight?: string;
  }[];
  fontWeight: { name: string; value: string }[];
  stylesheets: string[];
  icons: { predefined: {}; rest: [] };
};

export type ConfigType = {
  languages: LanguagesListType;
  domain: string;
  theme: {
    colors: Record<string, string>;
    fontFamily: Record<string, string[]>;
    fontSize: Record<
      string,
      | [
          string,
          {
            lineHeight?: string;
            letterSpacing?: string;
            fontWeight?: string;
          },
        ]
      | string
    >;
    fontWeight: Record<string, number>;
  };
  stylesheets: string;
  safelist: string[];
  icons: string[];
  gtmid: string;
};

/**
 * Get published theme from Sanity config.theme
 */

export async function getConfig(): Promise<ConfigType> {
  // get languages
  const languages: LanguagesListType = await client.fetch(`
  *[_id == "config_general"][0] {
    languages[] { id, title }
  }.languages`);

  // get robots.txt
  const domain: string = await client.fetch(`
  *[_id == "config_general"][0] { 
    domain
  }.domain`);

  // get gtmid
  const gtmid: string = await client.fetch(`
  *[_id == "config_integrations"][0] { 
    gtmid
  }.gtmid`);

  // get theme
  const theme: GroqThemeType = await client.fetch(`
  *[_id == "config_theme"][0] {
    colors[] { name, value },
    fontFamily[] { name, value },
    fontSize[] { name, size, lineHeight, letterSpacing, fontWeight },
    fontWeight[] { name, value },
    "stylesheets": stylesheets[] { value }.value,
  }`);

  if (!theme) {
    return {
      languages,
      domain,
      theme: {
        colors: {
          black: "#000000",
          white: "#ffffff",
        },
        fontFamily: {},
        fontWeight: {},
        fontSize: {},
      },
      safelist: [],
      stylesheets: "",
      icons: [],
      gtmid,
    };
  }

  const colors = formatColors(theme.colors || []);
  const fontFamily = formatFontFamily(theme.fontFamily || []);
  const fontWeight = formatFontWeight(theme.fontWeight || []);
  const fontSize = formatFontSize(theme.fontSize || []);
  const safelist =
    formatSafelist({ colors, fontFamily, fontSize, fontWeight }) || [];
  const stylesheets = `/* This file is automatically generated. */

  :root {
    ${theme.colors
      .map(({ name, value }) => `--color-${name}: ${value};`)
      .join("\n")}
    ${theme.fontFamily
      .map(({ name, value }) => `--font-${name}: ${value};`)
      .join("\n")}
    ${theme.fontWeight
      .map(({ name, value }) => `--font-weight-${name}: ${value};`)
      .join("\n")}
    ${theme.fontSize
      .map(({ name, size }) => `--font-size-${name}: ${size};`)
      .join("\n")}
  }

  ${theme.stylesheets ? theme.stylesheets?.join("\n\n") : ""}
  `;

  // get icon names
  let icons = await client.fetch(`
  *[_id == 'config_icons'][0] {
    predefined,
    "rest": rest[].slug.current
  }`);
  icons = [...Object.keys(icons?.predefined || {}), ...(icons?.rest || [])];

  return {
    languages,
    domain,
    theme: {
      colors,
      fontFamily,
      fontWeight,
      fontSize,
    },
    safelist,
    stylesheets,
    icons,
    gtmid,
  };
}

export default async function buildConfig() {
  const config = await getConfig();

  await fs.writeFile(
    `${__dirname}/../../engine.config.js`,
    `${DO_NOT_EDIT_FLAG}
    
export default ${JSON.stringify(config, null, 2)}`,
  );

  // write stylesheets to file
  await fs.writeFile(
    `${__dirname}/../../public/engine.styles.css`,
    config?.stylesheets,
  );

  // write locales to file for use in next.config.js
  await fs.writeFile(
    `${__dirname}/../../locales.js`,
    `${DO_NOT_EDIT_FLAG}
    
module.exports = ${JSON.stringify(
      config?.languages ? config.languages.map(({ id }) => id) : ["en"],
    )}`,
  );

  // replace domain in robots.txt
  const robotsTxt = await fs.readFile(`${__dirname}/../../public/robots.txt`);
  const robotsTxtLines = robotsTxt
    .toString()
    .split("\n")
    .map((line: string) => {
      if (line.startsWith("Host:")) {
        return `Host: https://${config?.domain ? config?.domain : ""}`;
      }

      if (line.startsWith("Sitemap:")) {
        return `Sitemap: https://${
          config?.domain ? config?.domain : ""
        }/sitemap.xml`;
      }

      return line;
    });

  await fs.writeFile(
    `${__dirname}/../../public/robots.txt`,
    robotsTxtLines.join("\n"),
  );

  // download opengraph fonts
  const fonts: {
    titleFont: { filename: string; font: string };
    metaFont: { filename: string; font: string };
  } = await client.fetch(`
  *[_id == "config_seo"][0] { 
    opengraphimage {
      titleFont {
        "filename": asset->originalFilename,
        "font": asset->url
      },
      metaFont {
        "filename": asset->originalFilename,
        "font": asset->url
      }
    }
  }.opengraphimage`);

  if (fonts?.titleFont) {
    await download(
      fonts.titleFont.font,
      `${__dirname}/../../public/downloads/ogTitleFont.ttf`,
    );
  } else {
    await copy(
      `${__dirname}/../../public/fonts/Inter-Bold.ttf`,
      `${__dirname}/../../public/downloads/ogTitleFont.ttf`,
    );
  }
  if (fonts?.metaFont) {
    await download(
      fonts.metaFont.font,
      `${__dirname}/../../public/downloads/ogMetaFont.ttf`,
    );
  } else {
    await copy(
      `${__dirname}/../../public/fonts/Inter-Medium.ttf`,
      `${__dirname}/../../public/downloads/ogMetaFont.ttf`,
    );
  }

  const favicon: string = await client.fetch(`
  *[_id == "config_seo"][0] { 
    "favicon": favicon.favicon_ico.asset->url,      
  }.favicon`);

  if (favicon) {
    await download(favicon, `${__dirname}/../../public/favicon.ico`);
  }
}

if (write) buildConfig();

let download = async function (url: string, filename: string) {
  let command = `curl -o ${filename}  '${url}'`;
  cp.execSync(command);
};

let copy = async function (from: string, to: string) {
  let command = `cp '${from}' '${to}'`;
  cp.execSync(command);
};
